version: '3.3'


services:
  api:
    image: ${INFERENCE_API_IMAGE_NAME}
    restart: always
    depends_on:
      - mongo
      - minio
      - nats
    env_file: 
      - .env
    command: python main.py
    ports:
      - 3000:${API_PORT}

  mongo:
    image: mongo
    restart: always
    env_file: 
      - .env

  mongo-express:
    image: mongo-express
    restart: always
    env_file: 
      - .env
    ports:
      - 8081:${ME_PORT}

  nats:
    image: nats:2.8.4
    restart: always
    ports:
      - 4222:${NATS_PORT_1}
      - 8222:${NATS_PORT_2}

  minio:
    image: minio/minio
    restart: always
    ports:
      - 9000:${MINIO_PORT_1}
      - 9001:${MINIO_PORT_2}
    command: server /data --console-address ':${MINIO_PORT_2}' --address ':${MINIO_PORT_1}'
    volumes:
      - minio_data:/data
    env_file: 
      - .env

  mlflow-mc:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      /tmp/wait-for-it.sh minio:${MINIO_PORT_1};
      /usr/bin/mc alias set minio ${MLFLOW_S3_ENDPOINT_URL} ${AWS_ACCESS_KEY_ID} ${AWS_SECRET_ACCESS_KEY};
      /usr/bin/mc mb minio/mlflow;
      exit 0;
      "
    volumes:
      - ./wait-for-it.sh:/tmp/wait-for-it.sh

  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:${MLFLOW_DB_PORT}
    env_file: 
      - .env
    volumes:
      - dbdata:/var/lib/mysql

  mlflow:
    image: ${MLFLOW_SERVER_IMAGE_NAME}
    restart: always
    ports:
      - 5000:${MLFLOW_PORT}
    env_file: 
      - .env
    command: mlflow server --backend-store-uri mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@db:${MLFLOW_DB_PORT}/${MYSQL_DATABASE} --default-artifact-root s3://mlflow/ --host 0.0.0.0

volumes:
  dbdata:
  minio_data:

  